/*Step 1 */
SELECT CRIME_ID, CLASSIFICATION, DATE_CHARGED, HEARING_DATE, (HEARING_DATE-DATE_CHARGED)
	FROM CRIMES
	WHERE (HEARING_DATE-DATE_CHARGED) > 14;

/*Step 2 */
SELECT PRECINCT,
	CASE 
		WHEN PRECINCT LIKE '_A%' THEN 'SHADY GROVE'
		WHEN PRECINCT LIKE '_B%' THEN 'CENTER CITY'
		WHEN PRECINCT LIKE '_C%' THEN 'BAY LANDING'
		ELSE 'NOT CURRENTLY ASSIGNED'
		END "COMMUNITY ASSIGNMENT"
FROM OFFICERS
WHERE STATUS='A';

/*Step 3 */
SELECT C.CRIMINAL_ID, UPPER(C.LAST), UPPER(C.FIRST), S.SENTENCE_ID, TO_CHAR(S.START_DATE, 'MONTH DD, YYYY') AS "START DATE", ROUND(MONTHS_BETWEEN(S.END_DATE,S.START_DATE)) AS "LENGTH OF SENTENCE"
FROM CRIMINALS C, SENTENCES S
WHERE C.CRIMINAL_ID=S.CRIMINAL_ID;


/*Step 4 */
SELECT LAST, FIRST, CHARGE_ID, TO_CHAR((FINE_AMOUNT+COURT_FEE), '$9999.99') AS "TOTAL AMOUNT OWED", TO_CHAR(AMOUNT_PAID,'$999.99') AS "AMOUNT PAID", TO_CHAR(((FINE_AMOUNT+COURT_FEE)-AMOUNT_PAID), '$9999.99') AS "AMOUNT OWED", PAY_DUE_DATE AS "PAY DUE DATE"
	FROM CRIMINALS NATURAL JOIN CRIMES NATURAL JOIN CRIME_CHARGES 
	WHERE ((FINE_AMOUNT+COURT_FEE)-AMOUNT_PAID) >0;

/*Step 5 */
SELECT C.LAST, C.FIRST, S.START_DATE, ADD_MONTHS(START_DATE, 2) AS "PROBATION REVIEW HEARING"
FROM CRIMINALS C NATURAL JOIN SENTENCES S
WHERE TYPE='P'
AND MONTHS_BETWEEN(END_DATE,START_DATE) > 2;

/*Step 6 */
INSERT INTO APPEALS (APPEAL_ID,CRIME_ID, FILING_DATE, HEARING_DATE)
	VALUES (APPEALS_ID_SEQ.NEXTVAL, :CRIME_ID, TO_DATE(:FILING_DATE, 'MM DD YYYY'), TO_DATE(:HEARING_DATE, 'MM DD YYYY'));
