/*STEP 1  TRADITIONAL*/

SELECT C.CRIMINAL_ID, C.LAST, C.FIRST, CC.CRIME_CODE, CC.FINE_AMOUNT
	FROM CRIMINALS C, CRIMES CR, CRIME_CHARGES CC
	WHERE CR.CRIME_ID=CC.CRIME_ID
	AND C.CRIMINAL_ID = CR.CRIMINAL_ID;

/*STEP 1 JOIN METHOD */

SELECT CRIMINAL_ID, LAST, FIRST, CRIME_CODE, FINE_AMOUNT
	FROM CRIMINALS NATURAL JOIN CRIMES NATURAL JOIN CRIME_CHARGES;

/*STEP 2 TRADITIONAL */
SELECT C.CRIMINAL_ID, C.LAST, C.FIRST, CR.CLASSIFICATION, CR.DATE_CHARGED, CR.CRIME_ID, A.FILING_DATE, A.STATUS
	FROM CRIMINALS C, CRIMES CR, APPEALS A
	WHERE C.CRIMINAL_ID=CR.CRIMINAL_ID
	AND CR.CRIME_ID=A.CRIME_ID(+)
	ORDER BY C.LAST;
	
/*STEP 2 JOIN */
SELECT CRIMINAL_ID, LAST, FIRST,CLASSIFICATION, DATE_CHARGED, CRIME_ID, FILING_DATE, A.STATUS
FROM CRIMINALS NATURAL JOIN CRIMES LEFT OUTER JOIN APPEALS A
USING(CRIME_ID)
ORDER BY LAST;


/*STEP 3 TRADITIONAL */
SELECT C.CRIMINAL_ID, C.LAST, C.FIRST, CR.CLASSIFICATION, CR.DATE_CHARGED, CC.CRIME_CODE, CC.FINE_AMOUNT
	FROM CRIMINALS C, CRIMES CR, CRIME_CHARGES CC
	WHERE CLASSIFICATION='O'
	AND CR.CRIME_ID=CC.CRIME_ID
	AND C.CRIMINAL_ID = CR.CRIMINAL_ID
	ORDER BY CRIMINAL_ID, DATE_CHARGED;

/*STEP 3 JOIN */

SELECT CRIMINAL_ID, LAST, FIRST, CLASSIFICATION, DATE_CHARGED, CRIME_CODE, FINE_AMOUNT
	FROM CRIMINALS NATURAL JOIN CRIMES NATURAL JOIN CRIME_CHARGES
	WHERE CLASSIFICATION='O';

/*STEP 4 TRADITIONAL */
SELECT C.CRIMINAL_ID, C.LAST, C.FIRST, C.V_STATUS, C.P_STATUS, AL.ALIAS
FROM CRIMINALS C, ALIASES AL
WHERE C.CRIMINAL_ID=AL.CRIMINAL_ID(+)
ORDER BY LAST;


/*STEP 4 JOIN */
SELECT CRIMINAL_ID, LAST, FIRST, V_STATUS, P_STATUS, ALIAS
FROM CRIMINALS FULL OUTER JOIN ALIASES USING (CRIMINAL_ID)
ORDER BY LAST;

/*STEP 5 TRADITIONAL */
SELECT C.LAST, C.FIRST, S.START_DATE, S.END_DATE, PR.CON_FREQ
FROM CRIMINALS C, PROB_CONTACT PR, SENTENCES S
WHERE C.CRIMINAL_ID=S.CRIMINAL_ID
AND S.TYPE='P'
AND (S.END_DATE - S.START_DATE) <= PR.HIGH_AMT
AND (S.END_DATE - S.START_DATE) >= PR.LOW_AMT
ORDER BY C.LAST, S.START_DATE;


/*STEP 5 JOIN */
SELECT C.LAST, C.FIRST, S.START_DATE, S.END_DATE, PR.CON_FREQ
FROM CRIMINALS C JOIN SENTENCES S ON S.TYPE='P' JOIN PROB_CONTACT PR ON (S.END_DATE - S.START_DATE) <= PR.HIGH_AMT
AND (S.END_DATE - S.START_DATE) >= PR.LOW_AMT
ORDER BY C.LAST, S.START_DATE;



/*STEP 6 TRADITIONAL */
SELECT PO.LAST, PO.FIRST, POM.LAST AS SUPERVISOR_LAST, POM.FIRST AS SUPERVISOR_FIRST
FROM PROB_OFFICERS PO, PROB_OFFICERS POM
WHERE PO.MGR_ID=POM.PROB_ID(+)
ORDER BY PO.LAST;

/*STEP 6 JOIN */
SELECT PO.LAST, PO.FIRST, POM.LAST AS SUPERVISOR_LAST, POM.FIRST AS SUPERVISOR_FIRST
FROM PROB_OFFICERS PO LEFT OUTER JOIN PROB_OFFICERS POM
ON PO.MGR_ID=POM.PROB_ID
ORDER BY PO.LAST;
